name: Build and Deploy

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Remove Src
        run: rm -rf src

      - name: Rename dist folder to app
        run: |
          if [ -d "dist" ]; then
            mv dist app
          fi

      - name: Create .vercel directory
        run: mkdir -p .vercel

      - name: Create project.json
        run: |
          echo '{
            "projectId": "${{ secrets.PROJECTID }}",
            "orgId": "${{ secrets.ORGID }}"
          }' > .vercel/project.json

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
